name: Release

on:
  release:
    types:
      - created

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: Shopify/github-workflows/.github/workflows/py-release-uv.yaml@py-release-uv
    with:
      environment: pypi
