name: Release

on:
  release:
    types:
      - created

permissions:
  contents: read
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0
      - run: uv python install

      - run: uv sync --all-extras --dev
      - run: uv build

      - uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70 # v1.12.3
